# Generated by Django 5.0.3 on 2024-04-05 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("from_user", "to_user")},
        ),
    ]
