# Generated by Django 5.0.3 on 2024-04-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_comment_created_at_alter_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
