# Generated by Django 5.0.3 on 2024-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0003_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
