# Generated by Django 5.0.3 on 2024-04-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0004_alter_profile_created_at_alter_profile_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="pid",
            new_name="uid",
        ),
    ]
